services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.11.1
    restart: unless-stopped
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--no-collector.zfs"
      - "--no-collector.btrfs"
      - "--no-collector.fibrechannel"
      - "--no-collector.infiniband"
      - "--no-collector.mdadm"
      - "--no-collector.nfs"
      - "--no-collector.nfsd"
      - "--no-collector.thermal_zone"
      - "--no-collector.edac"
      - "--no-collector.hwmon"
      - "--no-collector.powersupplyclass"
      - "--no-collector.tapestats"
    ports:
      - 9100:9100
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 16M

  cadvisor:
    container_name: cadvisor
    image: ghcr.io/google/cadvisor:0.56.2
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/proc:/rootfs/proc:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    command:
      - --disable_metrics=disk,referenced_memory
    ports:
      - "18080:8080"
    privileged: true
    devices:
      - "/dev/kmsg"
    deploy:
      resources:
        limits:
          memory: 196M
        reservations:
          memory: 64M
